openapi: 3.0.3
info:
  title: Slack Web API
  version: "1.0.0"
  description: |
    Partial OpenAPI spec for Slack API — search.messages method.


paths:
  /search.messages:
    get:
      summary: Search for messages
      description: |
        Searches for messages in Slack that match a given query.
        Requires the `search:read` scope.
      operationId: searchMessages
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: The query string to search for.
        - name: count
          in: query
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
          description: Number of items to return per page.
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Page number of results to return.
        - name: highlight
          in: query
          required: false
          schema:
            type: boolean
            default: true
          description: Whether to enable query highlight markers.
        - name: sort
          in: query
          required: false
          schema:
            type: string
            enum: [score, timestamp]
          description: Return matches sorted by either score or timestamp.
        - name: sort_dir
          in: query
          required: false
          schema:
            type: string
            enum: [asc, desc]
          description: Change sort direction to ascending (`asc`) or descending (`desc`).
      responses:
        "200":
          description: Search results.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  messages:
                    type: object
                    properties:
                      total:
                        type: integer
                      pagination:
                        type: object
                        properties:
                          total_count:
                            type: integer
                          page:
                            type: integer
                          per_page:
                            type: integer
                          page_count:
                            type: integer
                      matches:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                              example: message
                            user:
                              type: string
                              description: User ID of message sender.
                            text:
                              type: string
                            ts:
                              type: string
                              description: Message timestamp.
                            channel:
                              type: object
                              properties:
                                id:
                                  type: string
                                name:
                                  type: string
        "400":
          description: Invalid request
        "401":
          description: Unauthorized – missing or invalid token
      security:
        - slackAuth: []

components:
  securitySchemes:
    slackAuth:
      type: http
      scheme: bearer
      bearerFormat: "Slack Bot/User OAuth Token"
